# Generated by Django 3.1.2 on 2020-12-05 15:47

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50, verbose_name='Category name')),
                ('main_cat_desc', models.TextField(max_length=500, verbose_name='Description')),
                ('main_cat_img', models.ImageField(blank=True, null=True, upload_to='images/category/', verbose_name='Category image')),
                ('category_parent', models.ForeignKey(blank=True, limit_choices_to={'category_parent__isnull': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.category')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('email', models.EmailField(max_length=200)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_ordered', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('complete', models.BooleanField(blank=True, default=False, null=True, verbose_name='Complete')),
                ('transaction_id', models.CharField(max_length=200, null=True, verbose_name='Transaction id')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.customer', verbose_name='Customer')),
            ],
        ),
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200, null=True, verbose_name='Adress')),
                ('city', models.CharField(max_length=200, null=True, verbose_name='City')),
                ('state', models.CharField(max_length=200, null=True, verbose_name='State')),
                ('zipcode', models.CharField(max_length=200, null=True, verbose_name='Zipcode')),
                ('country', django_countries.fields.CountryField(max_length=2, null=True, verbose_name='Country')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Date added')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.customer', verbose_name='Customer')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.order', verbose_name='Order')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True, verbose_name='Product name')),
                ('description', models.TextField(default='', max_length=500, null=True, verbose_name='Description')),
                ('price', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Price')),
                ('coast', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Coast')),
                ('discount', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Discount')),
                ('digital', models.BooleanField(default=False, null=True, verbose_name='Digital')),
                ('image', models.ImageField(null=True, upload_to='images/product/', verbose_name='Image')),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Created at')),
                ('slug', models.SlugField(blank=True, null=True, verbose_name='Slug')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='settings.brand', verbose_name='Brand')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.category', verbose_name='Category')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, default=0, null=True, verbose_name='Quantity')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Date added')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.order', verbose_name='Order')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.product', verbose_name='Product')),
            ],
        ),
    ]
