# Generated by Django 3.1.2 on 2020-11-15 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20201115_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='coast',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=3, max_digits=4),
        ),
    ]
